# EBNF description of CSV+
[1] csv       ::= header record+
[2] header    ::= record
[3] record    ::= fields #x0D? #x0A
[4] fields    ::= field ("," fields)*
[5] field     ::= WS* rawfield WS*
[6] rawfield  ::= '"' QCHAR* '"'
                | SCHAR*
[7] QCHAR     ::= [^"] | '""'
[8] SCHAR     ::= [^",#x0A#x0D]
[9] WS        ::= [#x20#x09]
