# EBNF description of CSV+
[1] csv       ::= header record+
[2] header    ::= record
[3] record    ::= fields ("\r\n" | "\n")
[4] fields    ::= field ("," fields)*
[5] field     ::= WS* rawfield WS*
[6] rawfield  ::= '"' QCHAR* '"'
                | SCHAR*
[6] QCHAR     ::= [^"] | '""'
[7] SCHAR     ::= [^",\r\n]
[8] WS        ::= [ \t]
