BASE <http://foo.example/DB/>
CONSTRUCT {
  ?person <People#ref-deptName;deptCity> ?ref .
}
WHERE {
  ?person a <People>; <People#deptCity> ?city;  <People#deptName> ?name .
  [ a <Department>; <Department#city> ?city; <Department#name> ?name; <Department#ref-manager> ?departmentId ] .
  BIND (IRI("http://foo.example/DB/Department/ID=" + ?departmentId) as ?ref)
}
